
export default  [
    {
      raceDate: '16Dec20',
      raceCourse: 'Lingfield (AW) C5Hc 3K',
      raceDistance: '1m4f',
      going: 'St',
      wgt_hgr: '9-5 tp',
      pos_finishPos_winnerRunnerIp_wgt: '1/8 btn 17L Rafiot 9-2',
      sp: '40/1',
      jockey: 'W Carver',
      or: '73',
      ts: '26',
      rpr: '54',
      mr: '—'
    },

    {
      raceDate: '13Dec20',
      raceCourse: 'Foss Lass C52yNvAc 4K',
      raceDistance: '1m',
      going: 'St',
      wgt_hgr: '9-5 tp',
      pos_finishPos_winnerRunnerIp_wgt: '1/8 btn 17L Rafiot 9-2',
      sp: '40/1',
      jockey: 'W Carver',
      or: '73',
      ts: '26',
      rpr: '54',
      mr: '—'
    },

    {
      raceDate: '15Dec20',
      raceCourse: 'Lingfield (AW) C5Hc 3K',
      raceDistance: '1m4f',
      going: 'St',
      wgt_hgr: '9-5 tp',
      pos_finishPos_winnerRunnerIp_wgt: '1/8 btn 17L Rafiot 9-2',
      sp: '40/1',
      jockey: 'W Carver',
      or: '73',
      ts: '26',
      rpr: '54',
      mr: '—'
    },
  
    {
      raceDate: '10Nov20',
      raceCourse: 'Hereford C5HcH 4K',
      raceDistance: '2m',
      going: 'GS',
      wgt_hgr: '10-2 tp',
      pos_finishPos_winnerRunnerIp_wgt: '4/12 btn 12½L Sehayli 9-9',
      sp: '5/2F',
      jockey: 'F Gillard7',
      or: '104',
      ts: '75',
      rpr: '84',
      mr: '—'
    },
    {
      raceDate: '28Oct20',
      raceCourse: 'Fakenham C43yHM 4K',
      raceDistance: '2m',
      going: 'Gd',
      wgt_hgr: '10-3 tp1',
      pos_finishPos_winnerRunnerIp_wgt: '1/9 by 2½L Treaty Of Dingle 10-10',
      sp: '3/1',
      jockey: 'F Gillard7',
      or: '102',
      ts: '59',
      rpr: '92',
      mr: '—'
    },
    {
      raceDate: '20Oct20',
      raceCourse: 'Exeter C5HcH 3K',
      raceDistance: '2m2½f',
      going: 'GF',
      wgt_hgr: '10-7 t',
      pos_finishPos_winnerRunnerIp_wgt: '3/10 btn 11½L Caspers Court 11-9',
      sp: '9/4F',
      jockey: 'Mr M McIntyre3',
      or: '102',
      ts: '48',
      rpr: '77',
      mr: '—'
    },
    {
      raceDate: '29Sep20',
      raceCourse: 'Sedgefield C5HcH 3K',
      raceDistance: '2m1f',
      going: 'Gd',
      wgt_hgr: '10-6 t',
      pos_finishPos_winnerRunnerIp_wgt: '3/9 btn 3L Zamarkhan 10-13',
      sp: '15/8F',
      jockey: 'T Scudamore',
      or: '98',
      ts: '74',
      rpr: '79',
      mr: '—'
    },
    {
      raceDate: '16Aug20',
      raceCourse: 'Market Rasen C43yH 4K',
      raceDistance: '2m½f',
      going: 'Gd',
      wgt_hgr: '9-10 t',
      pos_finishPos_winnerRunnerIp_wgt: '2/8 btn 2½L Soldier On Parade 11-3',
      sp: '11/2',
      jockey: 'F Gillard7',
      or: '—',
      ts: '40',
      rpr: '92',
      mr: '—'
    },
    {
      raceDate: '07Aug20',
      raceCourse: 'Cartmel C43yH 4K',
      raceDistance: '2m1f',
      going: 'GS',
      wgt_hgr: '10-3 t1',
      pos_finishPos_winnerRunnerIp_wgt: '3/8 btn 24L Naizagai 10-7',
      sp: '11/1',
      jockey: 'T Scudamore',
      or: '—',
      ts: '66',
      rpr: '85',
      mr: '—'
    },
    {
      raceDate: '10Jul20',
      raceCourse: 'Clairefontaine 3y 8K',
      raceDistance: '1m',
      going: 'Gd',
      wgt_hgr: '8-3',
      pos_finishPos_winnerRunnerIp_wgt: '7/10 btn 7½L Bosioh 8-11',
      sp: '17/2',
      jockey: 'Damien Boche5',
      or: '—',
      ts: '—',
      rpr: '—',
      mr: '—'
    },
    {
      raceDate: '09Jun20',
      raceCourse: 'Nantes 3y 8K',
      raceDistance: '1m',
      going: 'GS',
      wgt_hgr: '8-4',
      pos_finishPos_winnerRunnerIp_wgt: '6/8 btn 5L Silver Schnok 8-3',
      sp: '43/5',
      jockey: 'Damien Boche5',
      or: '—',
      ts: '—',
      rpr: '66',
      mr: '—'
    },
    {
      raceDate: '23May20',
      raceCourse: 'Bordeaux Le Bouscat 3yL 16K',
      raceDistance: '1m1½f',
      going: 'Sft',
      wgt_hgr: '8-10',
      pos_finishPos_winnerRunnerIp_wgt: '6/6 btn 7¼L Fantastic Spirit 9-0',
      sp: '25/1',
      jockey: 'Damien Boche',
      or: '—',
      ts: '—',
      rpr: '79',
      mr: '—'
    },
    {
      raceDate: '09Sep19',
      raceCourse: 'Marseille Borely 2y 12K',
      raceDistance: '1m',
      going: 'GF',
      wgt_hgr: '8-10',
      pos_finishPos_winnerRunnerIp_wgt: '3/5 btn 6¼L Big Boss Man 9-0',
      sp: '16/1',
      jockey: 'Damien Boche',
      or: '—',
      ts: '—',
      rpr: '64',
      mr: '—'
    },
    {
      raceDate: '14Aug19',
      raceCourse: "Le Lion-D'Angers 2y ",
      raceDistance: '7f',
      going: 'GS',
      wgt_hgr: '8-10',
      pos_finishPos_winnerRunnerIp_wgt: '5/6 ',
      sp: '5/2',
      jockey: 'Damien Boche',
      or: '—',
      ts: '—',
      rpr: '—',
      mr: '—'
    },
    {
      raceDate: '14Jul19',
      raceCourse: 'Senonnes-Pouance 2y 6K',
      raceDistance: '7f',
      going: 'Gd',
      wgt_hgr: '8-4',
      pos_finishPos_winnerRunnerIp_wgt: '1/8 ',
      sp: '—',
      jockey: 'Damien Boche7',
      or: '—',
      ts: '—',
      rpr: '—',
      mr: '—'
    }
  ]

 