
export const today = {
    racecourseId: '8',
    racecourseName: 'carlisle',
    raceDate: '2021-02-16',
    raceDistance:'2m1f',
    raceDistanceM:3300, 
    raceId: 776572,
    prizeMoney: undefined,
    noRunners: 5,
    going: "heavy",
    hurdles: false,
    noHurdles: null,
    isFlat: true
}
//The Runner Data
export const runners = [
{
  todaysTrainer: {
    trainerID: 18875,
    trainerName: 'philip-kirby',
    trainerWins: '2',
    trainerRuns: '27',
    trainerSR: '7'
  },
  todaysJockey: {
    jockeyID: 95218,
    jockeyName: 'joe-williamson',
    jockeyWins: '0',
    jockeyRuns: '6',
    jockeySR: '0'
  },
  horseId: 3265144,
  horseName: 'first-glory',
  ownerUrl: 'https://www.racingpost.com/profile/owner/291812/alan-rogers',
  breederName: 'Ms Lauren Cousins',
  previousEvents: [],
  stats: {
    runs: 1,
    wins: 1,
    places: 0,
    sr: 100,
    winnings: '2924.00',
    earnings: '2924.00',
    avgWinnings: 2924,
    avgEarnings: 2924,
    bestRpr: NaN,
    bestTs: NaN
  },
  raceRecordTable: [
    {
      lifetimeRecord: 'NHF',
      runs: '1',
      wins: '1',
      seconds: '0',
      thirds: '0',
      winnings: '£2,924',
      prize: '3K',
      earnings: '£2,924',
      or: '—',
      bestTs: '—',
      bestRpr: '92',
      bestMr: '—'
    },
    {
      lifetimeRecord: 'PTP',
      runs: '2',
      wins: '0',
      seconds: '0',
      thirds: '1',
      winnings: '—',
      prize: null,
      earnings: '—',
      or: '—',
      bestTs: '—',
      bestRpr: '77',
      bestMr: '—'
    },
    {
      lifetimeRecord: 'Rules Races',
      runs: '1',
      wins: '1',
      seconds: '0',
      thirds: '0',
      winnings: '£2,924',
      prize: '3K',
      earnings: '£2,924',
      or: '—',
      bestTs: '—',
      bestRpr: '—',
      bestMr: '—'
    }
  ],
  formTable: [
    {
      horseId: 3265144,
      lRacecourseId: 393,
      lRaceCourseName: 'lingfield-aw',
      lRaceDate: '2021-01-18',
      lraceId: 774403,
      lJockeyId: 95218,
      lJockeyName: 'joe-williamson',
      lPrizeMoney: 3000,
      lRaceDistance: '2m',
      lRaceDistanceMeters: '2m',
      lGoing: 'St/Slw',
      lWghtMetric: '65.77',
      lHgr: null,
      lWght: '10-5',
      gearSwitch: false,
      lFinalPos: '1',
      lRan: 12,
      lBeatenBy: undefined,
      lIsNonRunner: false,
      lIsWinner: true,
      lSP: '11/1',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: 7,
      lOR: null,
      lTS: null,
      lRPR: 92,
      lRaceName: "EBF Mares' Standard Open National Hunt Flat Race (GBB Race)",
      lIsMdn: false,
      lTrackDesc: '',
      lRunComment: 'made all, ridden from 2 out, hard pressed over 1f out, kept on strongly inside final furlong, all out, just held on (op 10/1 tchd 9/1)',
      raceDate: '18Jan21',
      raceCourse: 'Lingfield (AW) C5NHFM 3K',
      raceDistance: '2m',
      going: 'St/Slw',
      wgt_hgr: '10-5',
      pos_finishPos_winnerRunnerIp_wgt: '1/12 by nk Okhotsk 10-9',
      sp: '11/1',
      jockey: 'J Williamson7',
      or: '—',
      ts: '—',
      rpr: '92',
      mr: '—'
    },
    {
      horseId: 3265144,
      lRacecourseId: 343,
      lRaceCourseName: 'tinahely',
      lRaceDate: '2020-11-15',
      lraceId: 772219,
      lJockeyId: 87306,
      lJockeyName: 'j-j-walsh',
      lPrizeMoney: null,
      lRaceDistance: '3m',
      lRaceDistanceMeters: '3m',
      lGoing: 'Sft/Hy',
      lWghtMetric: '74.84',
      lHgr: null,
      lWght: '11-11',
      gearSwitch: false,
      lFinalPos: '3',
      lRan: 10,
      lBeatenBy: '5',
      lIsNonRunner: false,
      lIsWinner: false,
      lSP: '—',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: null,
      lOR: null,
      lTS: null,
      lRPR: 77,
      lRaceName: 'Tattersalls Ireland 4yo Mares Maiden',
      lIsMdn: true,
      lTrackDesc: 'RH, undulating, galloping, uphill finish',
      lRunComment: 'pr early, ld 4th, jnd 7th, hdd 2out, dropped to 3rd and no extra last',
      raceDate: '15Nov20',
      raceCourse: 'Tinahely 4yMdPTP ',
      raceDistance: '3m',
      going: 'Sft/Hy',
      wgt_hgr: '11-11',
      pos_finishPos_winnerRunnerIp_wgt: "3/10 btn 5L Fashion's Model 11-11",
      sp: '—',
      jockey: 'J J Walsh',
      or: '—',
      ts: '—',
      rpr: '77',
      mr: '—'
    },
    {
      horseId: 3265144,
      lRacecourseId: 370,
      lRaceCourseName: 'loughanmore',
      lRaceDate: '2020-10-24',
      lraceId: 770316,
      lJockeyId: 87306,
      lJockeyName: 'j-j-walsh',
      lPrizeMoney: null,
      lRaceDistance: '3m',
      lRaceDistanceMeters: '3m',
      lGoing: 'Y/Sft',
      lWghtMetric: '74.84',
      lHgr: null,
      lWght: '11-11',
      gearSwitch: false,
      lFinalPos: 'UR',
      lRan: 8,
      lBeatenBy: undefined,
      lIsNonRunner: false,
      lIsWinner: false,
      lSP: '—',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: null,
      lOR: null,
      lTS: null,
      lRPR: null,
      lRaceName: 'Tattersalls Ireland 4yo Mares Maiden',
      lIsMdn: true,
      lTrackDesc: 'LH, flat, galloping',
      lRunComment: 'ld early, jnd aftr 3rd, pr when mstk & ur 5th',
      raceDate: '24Oct20',
      raceCourse: 'Loughanmore 4yMdPTP ',
      raceDistance: '3m',
      going: 'Y/Sft',
      wgt_hgr: '11-11',
      pos_finishPos_winnerRunnerIp_wgt: 'UR/8 The Mean Queen 11-11',
      sp: '—',
      jockey: 'J J Walsh',
      or: '—',
      ts: '—',
      rpr: '—',
      mr: '—'
    }
  ],
  declaredComment: 'Comment:Made all on Lingfield AW on bumper debut but they finished in a heap; now carries penalty'
},

//The Runner Data
{
  todaysTrainer: {
    trainerID: 16596,
    trainerName: 's-r-b-crawford',
    trainerWins: '1',
    trainerRuns: '12',
    trainerSR: '8'
  },
  todaysJockey: {
    jockeyID: 12290,
    jockeyName: 'richard-johnson',
    jockeyWins: '4',
    jockeyRuns: '20',
    jockeySR: '20'
  },
  horseId: 3248385,
  horseName: 'burnt-ash',
  ownerUrl: 'https://www.racingpost.com/profile/owner/90006/miss-e-hamilton',
  breederName: 'D Mitchell',
  previousEvents: [],
  stats: {
    runs: 0,
    wins: 0,
    places: 0,
    sr: 0,
    winnings: 0,
    earnings: 0,
    avgWinnings: 0,
    avgEarnings: 0,
    bestRpr: 0,
    bestTs: 0
  },
  raceRecordTable: [
    {
      lifetimeRecord: 'PTP',
      runs: '3',
      wins: '0',
      seconds: '0',
      thirds: '1',
      winnings: '—',
      prize: null,
      earnings: '—',
      or: '—',
      bestTs: '—',
      bestRpr: '73',
      bestMr: '—'
    }
  ],
  formTable: [
    {
      horseId: 3248385,
      lRacecourseId: 1093,
      lRaceCourseName: 'kirkistown',
      lRaceDate: '2020-11-21',
      lraceId: 772616,
      lJockeyId: 81979,
      lJockeyName: 'b-oneill',
      lPrizeMoney: null,
      lRaceDistance: '3m',
      lRaceDistanceMeters: '3m',
      lGoing: 'Sft',
      lWghtMetric: '74.84',
      lHgr: null,
      lWght: '11-11',
      gearSwitch: false,
      lFinalPos: 'F',
      lRan: 9,
      lBeatenBy: undefined,
      lIsNonRunner: false,
      lIsWinner: false,
      lSP: '—',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: null,
      lOR: null,
      lTS: null,
      lRPR: null,
      lRaceName: 'Tattersalls Ireland 5yo+ Mares Maiden',
      lIsMdn: true,
      lTrackDesc: 'LH, flat, galloping',
      lRunComment: 'ww in rr, 9th 1/2way, left 8l 4th aftr 4out, mod 4th when fell 3out',
      raceDate: '21Nov20',
      raceCourse: 'Kirkistown MdPTP ',
      raceDistance: '3m',
      going: 'Sft',
      wgt_hgr: '11-11',
      pos_finishPos_winnerRunnerIp_wgt: 'F/9 Kates Hill 11-11',
      sp: '—',
      jockey: "B O'Neill",
      or: '—',
      ts: '—',
      rpr: '—',
      mr: '—'
    },
    {
      horseId: 3248385,
      lRacecourseId: 370,
      lRaceCourseName: 'loughanmore',
      lRaceDate: '2020-10-24',
      lraceId: 770318,
      lJockeyId: 87835,
      lJockeyName: 'b-g-crawford',
      lPrizeMoney: null,
      lRaceDistance: '3m',
      lRaceDistanceMeters: '3m',
      lGoing: 'Y/Sft',
      lWghtMetric: '74.84',
      lHgr: null,
      lWght: '11-11',
      gearSwitch: false,
      lFinalPos: '3',
      lRan: 5,
      lBeatenBy: '4¾',
      lIsNonRunner: false,
      lIsWinner: false,
      lSP: '—',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: null,
      lOR: null,
      lTS: null,
      lRPR: 73,
      lRaceName: 'John Thompson & Sons 5yo+ Mares Maiden',
      lIsMdn: true,
      lTrackDesc: 'LH, flat, galloping',
      lRunComment: 'mid-div, sl mstk 4th, 3rd 1/2way, drpd to last aftr 3out, rdn 2out, sl mstk in 4th last, ko to 3rd cl hm',
      raceDate: '24Oct20',
      raceCourse: 'Loughanmore MdPTP ',
      raceDistance: '3m',
      going: 'Y/Sft',
      wgt_hgr: '11-11',
      pos_finishPos_winnerRunnerIp_wgt: '3/5 btn 4¾L Miss Us O 11-11',
      sp: '—',
      jockey: 'B Crawford',
      or: '—',
      ts: '—',
      rpr: '73',
      mr: '—'
    },
    {
      horseId: 3248385,
      lRacecourseId: 550,
      lRaceCourseName: 'moira',
      lRaceDate: '2020-10-10',
      lraceId: 769145,
      lJockeyId: 87835,
      lJockeyName: 'b-g-crawford',
      lPrizeMoney: null,
      lRaceDistance: '3m',
      lRaceDistanceMeters: '3m',
      lGoing: 'Y/Sft',
      lWghtMetric: '74.84',
      lHgr: null,
      lWght: '11-11',
      gearSwitch: false,
      lFinalPos: 'PU',
      lRan: 8,
      lBeatenBy: undefined,
      lIsNonRunner: false,
      lIsWinner: false,
      lSP: '—',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: null,
      lOR: null,
      lTS: null,
      lRPR: null,
      lRaceName: 'Tattersalls Ireland 5&6yo Mares Maiden',
      lIsMdn: true,
      lTrackDesc: 'LH, undulating,, downhill finish',
      lRunComment: 'twr rr, drpd to rr aftr 3rd, last 1/2way, 15l dwn when mstk 7out, rdn aftr 5out, mstk 4out, pu sn after',
      raceDate: '10Oct20',
      raceCourse: 'Moira MdPTP ',
      raceDistance: '3m',
      going: 'Y/Sft',
      wgt_hgr: '11-11',
      pos_finishPos_winnerRunnerIp_wgt: 'PU/8 Call Me Merry 11-11',
      sp: '—',
      jockey: 'B Crawford',
      or: '—',
      ts: '—',
      rpr: '—',
      mr: '—'
    }
  ],
  declaredComment: 'Comment:Hint of ability in points; one of three declared by yard; one to watch in the betting'
},


//The Runner Data
{
  todaysTrainer: {
    trainerID: 16596,
    trainerName: 's-r-b-crawford',
    trainerWins: '1',
    trainerRuns: '12',
    trainerSR: '8'
  },
  todaysJockey: {
    jockeyID: 81266,
    jockeyName: 'daryl-jacob',
    jockeyWins: '1',
    jockeyRuns: '17',
    jockeySR: '6'
  },
  horseId: 3399505,
  horseName: 'condesa',
  ownerUrl: 'https://www.racingpost.com/profile/owner/206920/simon-munir-isaac-souede',
  breederName: "Mrs Mary O'Connor",
  previousEvents: [],
  stats: {
    runs: 0,
    wins: 0,
    places: 0,
    sr: 0,
    winnings: 0,
    earnings: 0,
    avgWinnings: 0,
    avgEarnings: 0,
    bestRpr: 0,
    bestTs: 0
  },
  raceRecordTable: [
    {
      lifetimeRecord: 'No race record for this horse',
      runs: undefined,
      wins: undefined,
      seconds: undefined,
      thirds: undefined,
      winnings: undefined,
      prize: undefined,
      earnings: undefined,
      or: undefined,
      bestTs: undefined,
      bestRpr: undefined,
      bestMr: undefined
    }
  ],
  formTable: [],
  declaredComment: 'Comment:Has a useful pedigree; one of the three for yard; betting should be informative on debut'
},
//The Runner Data
{
  todaysTrainer: {
    trainerID: 21345,
    trainerName: 'rose-dobbin',
    trainerWins: '0',
    trainerRuns: '6',
    trainerSR: '0'
  },
  todaysJockey: {
    jockeyID: 85846,
    jockeyName: 'conor-ofarrell',
    jockeyWins: '1',
    jockeyRuns: '16',
    jockeySR: '6'
  },
  horseId: 2564356,
  horseName: 'dream-over',
  ownerUrl: 'https://www.racingpost.com/profile/owner/17397/mrs-ian-mckie',
  breederName: 'Coisdeel Bloodstock Limited',
  previousEvents: [
    {
      eventDate: '25Jan21',
      eventName: 'Changed Trainer notification: Jessica McKie to Rose Dobbin'
    },
    {
      eventDate: '12Dec20',
      eventName: 'Changed Trainer notification: Victoria McKie to Jessica McKie'
    }
  ],
  stats: {
    runs: 0,
    wins: 0,
    places: 0,
    sr: 0,
    winnings: 0,
    earnings: 0,
    avgWinnings: 0,
    avgEarnings: 0,
    bestRpr: 0,
    bestTs: 0
  },
  raceRecordTable: [
    {
      lifetimeRecord: 'PTP',
      runs: '5',
      wins: '2',
      seconds: '0',
      thirds: '0',
      winnings: '—',
      prize: null,
      earnings: '—',
      or: '—',
      bestTs: '—',
      bestRpr: '—',
      bestMr: '—'
    }
  ],
  formTable: [
    {
      horseId: 2564356,
      lRacecourseId: 53,
      lRaceCourseName: 'alnwick',
      lRaceDate: '2020-12-13',
      lraceId: 774378,
      lJockeyId: 84440,
      lJockeyName: 'n-orpwood',
      lPrizeMoney: null,
      lRaceDistance: '3m',
      lRaceDistanceMeters: '3m',
      lGoing: 'Sft',
      lWghtMetric: '73.03',
      lHgr: null,
      lWght: '11-7',
      gearSwitch: false,
      lFinalPos: '1',
      lRan: 7,
      lBeatenBy: undefined,
      lIsNonRunner: false,
      lIsWinner: true,
      lSP: '—',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: null,
      lOR: null,
      lTS: null,
      lRPR: null,
      lRaceName: 'Restricted',
      lIsMdn: false,
      lTrackDesc: 'LH, undulating, fairly sharp',
      lRunComment: 'a.p; led aft 3 out; stayed on wl',
      raceDate: '13Dec20',
      raceCourse: 'Alnwick ResPTP ',
      raceDistance: '3m',
      going: 'Sft',
      wgt_hgr: '11-7',
      pos_finishPos_winnerRunnerIp_wgt: '1/7 by 5L Matthew Man 12-0',
      sp: '—',
      jockey: 'N Orpwood',
      or: '—',
      ts: '—',
      rpr: '—',
      mr: '—'
    },
    {
      horseId: 2564356,
      lRacecourseId: 167,
      lRaceCourseName: 'friars-haugh',
      lRaceDate: '2020-01-26',
      lraceId: 750296,
      lJockeyId: 84440,
      lJockeyName: 'n-orpwood',
      lPrizeMoney: null,
      lRaceDistance: '2m4f',
      lRaceDistanceMeters: '2m4f',
      lGoing: 'GS',
      lWghtMetric: '69.85',
      lHgr: null,
      lWght: '11-0',
      gearSwitch: false,
      lFinalPos: '1',
      lRan: 11,
      lBeatenBy: undefined,
      lIsNonRunner: false,
      lIsWinner: true,
      lSP: '5/1',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: null,
      lOR: null,
      lTS: null,
      lRPR: null,
      lRaceName: 'Open Maiden',
      lIsMdn: true,
      lTrackDesc: 'LH, mostly flat (similar to neighbouring Kelso NH)',
      lRunComment: 'hdwy 4 out; led app 2 out; r.o wl',
      raceDate: '26Jan20',
      raceCourse: 'Friars Haugh MdOpenPTP ',
      raceDistance: '2m4f',
      going: 'GS',
      wgt_hgr: '11-0',
      pos_finishPos_winnerRunnerIp_wgt: '1/11 by 2½L Teds Charley Roe 12-0',
      sp: '5/1',
      jockey: 'N Orpwood',
      or: '—',
      ts: '—',
      rpr: '—',
      mr: '—'
    },
    {
      horseId: 2564356,
      lRacecourseId: 53,
      lRaceCourseName: 'alnwick',
      lRaceDate: '2019-12-15',
      lraceId: 747397,
      lJockeyId: 84440,
      lJockeyName: 'n-orpwood',
      lPrizeMoney: null,
      lRaceDistance: '3m',
      lRaceDistanceMeters: '3m',
      lGoing: 'Sft',
      lWghtMetric: '69.85',
      lHgr: null,
      lWght: '11-0',
      gearSwitch: false,
      lFinalPos: 'PU',
      lRan: 12,
      lBeatenBy: undefined,
      lIsNonRunner: false,
      lIsWinner: false,
      lSP: '5/1',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: null,
      lOR: null,
      lTS: null,
      lRPR: null,
      lRaceName: 'Open Maiden (Div 1)',
      lIsMdn: true,
      lTrackDesc: 'LH, undulating, fairly sharp',
      lRunComment: 'nvr trbld ldrs; t.o & pu 3 out',
      raceDate: '15Dec19',
      raceCourse: 'Alnwick MdOpenPTP ',
      raceDistance: '3m',
      going: 'Sft',
      wgt_hgr: '11-0',
      pos_finishPos_winnerRunnerIp_wgt: 'PU/12 Take Your Time 11-7',
      sp: '5/1',
      jockey: 'N Orpwood',
      or: '—',
      ts: '—',
      rpr: '—',
      mr: '—'
    },
    {
      horseId: 2564356,
      lRacecourseId: 75,
      lRaceCourseName: 'tranwell',
      lRaceDate: '2019-04-07',
      lraceId: 727240,
      lJockeyId: 84440,
      lJockeyName: 'n-orpwood',
      lPrizeMoney: null,
      lRaceDistance: '2m4f',
      lRaceDistanceMeters: '2m4f',
      lGoing: 'Gd',
      lWghtMetric: '67.59',
      lHgr: null,
      lWght: '10-9 h',
      gearSwitch: false,
      lFinalPos: '5',
      lRan: 9,
      lBeatenBy: '2',
      lIsNonRunner: false,
      lIsWinner: false,
      lSP: '3/1',
      lSPDec: 4,
      lIsFav: true,
      lJockeyClaim: null,
      lOR: null,
      lTS: null,
      lRPR: null,
      lRaceName: 'Open Maiden',
      lIsMdn: true,
      lTrackDesc: 'LH, flat, galloping',
      lRunComment: 'held up; 8l last 1/2way; hdwy 3 out; 5l 4th nxt; kpt on flat',
      raceDate: '07Apr19',
      raceCourse: 'Tranwell MdOpenPTP ',
      raceDistance: '2m4f',
      going: 'Gd',
      wgt_hgr: '10-9 h',
      pos_finishPos_winnerRunnerIp_wgt: '5/9 btn 2L Raleagh Mountain 12-0',
      sp: '3/1F',
      jockey: 'N Orpwood',
      or: '—',
      ts: '—',
      rpr: '—',
      mr: '—'
    },
    {
      horseId: 2564356,
      lRacecourseId: 53,
      lRaceCourseName: 'alnwick',
      lRaceDate: '2019-03-10',
      lraceId: 724948,
      lJockeyId: 86340,
      lJockeyName: 'miss-a-waugh',
      lPrizeMoney: null,
      lRaceDistance: '2m',
      lRaceDistanceMeters: '2m',
      lGoing: 'GS',
      lWghtMetric: '68.49',
      lHgr: null,
      lWght: '10-11',
      gearSwitch: false,
      lFinalPos: '6',
      lRan: 8,
      lBeatenBy: '28',
      lIsNonRunner: false,
      lIsWinner: false,
      lSP: '12/1',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: null,
      lOR: null,
      lTS: null,
      lRPR: null,
      lRaceName: 'The JRL Group Flat Race 45&6yo',
      lIsMdn: false,
      lTrackDesc: 'LH, undulating, fairly sharp',
      lRunComment: 'in tch 12f',
      raceDate: '10Mar19',
      raceCourse: 'Alnwick PTP ',
      raceDistance: '2m',
      going: 'GS',
      wgt_hgr: '10-11',
      pos_finishPos_winnerRunnerIp_wgt: '6/8 btn 28L King Erik 11-12',
      sp: '12/1',
      jockey: 'Miss A Waugh',
      or: '—',
      ts: '—',
      rpr: '—',
      mr: '—'
    }
  ],
  declaredComment: 'Comment:Two-time point winner who could have a part to play on bumper debut'
},

//The Runner Data
{
  todaysTrainer: {
    trainerID: 29513,
    trainerName: 'adrian-paul-keatley',
    trainerWins: '0',
    trainerRuns: '1',
    trainerSR: '0'
  },
  todaysJockey: {
    jockeyID: 96446,
    jockeyName: 'aaron-anderson',
    jockeyWins: '0',
    jockeyRuns: '11',
    jockeySR: '0'
  },
  horseId: 3396915,
  horseName: 'lisnagoorneen',
  ownerUrl: 'https://www.racingpost.com/profile/owner/300807/w-j-fouhy',
  breederName: 'J Fouhy',
  previousEvents: [],
  stats: {
    runs: 0,
    wins: 0,
    places: 0,
    sr: 0,
    winnings: 0,
    earnings: 0,
    avgWinnings: 0,
    avgEarnings: 0,
    bestRpr: 0,
    bestTs: 0
  },
  raceRecordTable: [
    {
      lifetimeRecord: 'No race record for this horse',
      runs: undefined,
      wins: undefined,
      seconds: undefined,
      thirds: undefined,
      winnings: undefined,
      prize: undefined,
      earnings: undefined,
      or: undefined,
      bestTs: undefined,
      bestRpr: undefined,
      bestMr: undefined
    }
  ],
  formTable: [],
  declaredComment: 'Comment:7th foal; half-sister to bumper winner Vrai Vert (RPR 120); market should provide clues'
},


//The Runner Data
{
  todaysTrainer: {
    trainerID: 25170,
    trainerName: 'oliver-greenall',
    trainerWins: '0',
    trainerRuns: '12',
    trainerSR: '0'
  },
  todaysJockey: {
    jockeyID: 87437,
    jockeyName: 'henry-brooke',
    jockeyWins: '0',
    jockeyRuns: '0',
    jockeySR: undefined
  },
  horseId: 2644659,
  horseName: 'wasastylequeen',
  ownerUrl: 'https://www.racingpost.com/profile/owner/269754/the-burling-family-ltd',
  breederName: 'Yorton Farm Stud',
  previousEvents: [
    {
      eventDate: '05Feb21',
      eventName: 'Changed Trainer notification: Joshua Guerriero to Oliver Greenall'
    }
  ],
  stats: {
    runs: 0,
    wins: 0,
    places: 0,
    sr: 0,
    winnings: 0,
    earnings: 0,
    avgWinnings: 0,
    avgEarnings: 0,
    bestRpr: 0,
    bestTs: 0
  },
  raceRecordTable: [
    {
      lifetimeRecord: 'PTP',
      runs: '1',
      wins: '1',
      seconds: '0',
      thirds: '0',
      winnings: '—',
      prize: null,
      earnings: '—',
      or: '—',
      bestTs: '—',
      bestRpr: '—',
      bestMr: '—'
    }
  ],
  formTable: [
    {
      horseId: 2644659,
      lRacecourseId: 106,
      lRaceCourseName: 'sandon',
      lRaceDate: '2019-04-20',
      lraceId: 728630,
      lJockeyId: 86421,
      lJockeyName: 'e-glassonbury',
      lPrizeMoney: null,
      lRaceDistance: '2m5f',
      lRaceDistanceMeters: '2m5f',
      lGoing: 'Gd',
      lWghtMetric: '66.22',
      lHgr: null,
      lWght: '10-6',
      gearSwitch: false,
      lFinalPos: '1',
      lRan: 4,
      lBeatenBy: undefined,
      lIsNonRunner: false,
      lIsWinner: true,
      lSP: '6/4',
      lSPDec: 2.5,
      lIsFav: true,
      lJockeyClaim: null,
      lOR: null,
      lTS: null,
      lRPR: null,
      lRaceName: 'Open Maiden 456&7yo',
      lIsMdn: true,
      lTrackDesc: 'RH, minor undulations; 3m nearer to 3m2f',
      lRunComment: 'a.p; led app 2 out; rdn out',
      raceDate: '20Apr19',
      raceCourse: 'Sandon MdOpenPTP ',
      raceDistance: '2m5f',
      going: 'Gd',
      wgt_hgr: '10-6',
      pos_finishPos_winnerRunnerIp_wgt: '1/4 by 2¼L Exit Plan 12-0',
      sp: '6/4F',
      jockey: 'E Glassonbury',
      or: '—',
      ts: '—',
      rpr: '—',
      mr: '—'
    }
  ],
  declaredComment: 'Comment:Point winner in April 2019 but absent since and the form is weak'
},
//The Runner Data
{
  todaysTrainer: {
    trainerID: 16596,
    trainerName: 's-r-b-crawford',
    trainerWins: '1',
    trainerRuns: '12',
    trainerSR: '8'
  },
  todaysJockey: {
    jockeyID: 81409,
    jockeyName: 'brian-hughes',
    jockeyWins: '5',
    jockeyRuns: '34',
    jockeySR: '15'
  },
  horseId: 3406857,
  horseName: 'gazwah',
  ownerUrl: 'https://www.racingpost.com/profile/owner/211899/b-arthey',
  breederName: 'Al Shaqab Racing',
  previousEvents: [],
  stats: {
    runs: 0,
    wins: 0,
    places: 0,
    sr: 0,
    winnings: 0,
    earnings: 0,
    avgWinnings: 0,
    avgEarnings: 0,
    bestRpr: 0,
    bestTs: 0
  },
  raceRecordTable: [
    {
      lifetimeRecord: 'No race record for this horse',
      runs: undefined,
      wins: undefined,
      seconds: undefined,
      thirds: undefined,
      winnings: undefined,
      prize: undefined,
      earnings: undefined,
      or: undefined,
      bestTs: undefined,
      bestRpr: undefined,
      bestMr: undefined
    }
  ],
  formTable: [],
  declaredComment: 'Comment:One of three declared by yard; the betting could help sort out the pecking order'
},
//The Runner Data
{
  todaysTrainer: {
    trainerID: 6990,
    trainerName: 'lucinda-russell',
    trainerWins: '1',
    trainerRuns: '13',
    trainerSR: '8'
  },
  todaysJockey: {
    jockeyID: 88869,
    jockeyName: 'stephen-mulqueen',
    jockeyWins: '0',
    jockeyRuns: '5',
    jockeySR: '0'
  },
  horseId: 3315587,
  horseName: 'haute-estime',
  ownerUrl: 'https://www.racingpost.com/profile/owner/33603/peter-j-s-russell',
  breederName: 'Denis Duggan',
  previousEvents: [],
  stats: {
    runs: 1,
    wins: 0,
    places: 1,
    sr: 0,
    winnings: 'NaN',
    earnings: '859.00',
    avgWinnings: NaN,
    avgEarnings: 859,
    bestRpr: NaN,
    bestTs: NaN
  },
  raceRecordTable: [
    {
      lifetimeRecord: 'NHF',
      runs: '1',
      wins: '0',
      seconds: '1',
      thirds: '0',
      winnings: '—',
      prize: '1K',
      earnings: '£859',
      or: '—',
      bestTs: '3',
      bestRpr: '95',
      bestMr: '—'
    },
    {
      lifetimeRecord: 'Rules Races',
      runs: '1',
      wins: '0',
      seconds: '1',
      thirds: '0',
      winnings: '—',
      prize: '1K',
      earnings: '£859',
      or: '—',
      bestTs: '—',
      bestRpr: '—',
      bestMr: '—'
    }
  ],
  formTable: [
    {
      horseId: 3315587,
      lRacecourseId: 87,
      lRaceCourseName: 'wetherby',
      lRaceDate: '2020-12-05',
      lraceId: 770647,
      lJockeyId: 88869,
      lJockeyName: 'stephen-mulqueen',
      lPrizeMoney: 3000,
      lRaceDistance: '1m4½f',
      lRaceDistanceMeters: '1m4½f',
      lGoing: 'Sft',
      lWghtMetric: '67.59',
      lHgr: null,
      lWght: '10-9',
      gearSwitch: false,
      lFinalPos: '2',
      lRan: 12,
      lBeatenBy: '16',
      lIsNonRunner: false,
      lIsWinner: false,
      lSP: '50/1',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: 3,
      lOR: null,
      lTS: 3,
      lRPR: 95,
      lRaceName: `Watch Racing TV In Stunning HD Fillies' "Junior" Standard Open National Hunt Flat Race (GBB Race)`,
      lIsMdn: false,
      lTrackDesc: 'left-handed, galloping track with stiff fences',
      lRunComment: 'midfield, tracked leaders over 5f out, pushed along over 3f out, ridden 2f out, stayed on and went second inside final 110yds, no match for winner (op 28/1)',
      raceDate: '05Dec20',
      raceCourse: 'Wetherby C53yNHFM 3K',
      raceDistance: '1m4½f',
      going: 'Sft',
      wgt_hgr: '10-9',
      pos_finishPos_winnerRunnerIp_wgt: '2/12 btn 16L Eileendover 11-2',
      sp: '50/1',
      jockey: 'S Mulqueen3',
      or: '—',
      ts: '3',
      rpr: '95',
      mr: '—'
    }
  ],
  declaredComment: 'Comment:Bumped into very useful prospect when 16l second on debut at Wetherby; respected'
},



///The Runner Data
{
  todaysTrainer: {
    trainerID: 32733,
    trainerName: 'samuel-drinkwater',
    trainerWins: '0',
    trainerRuns: '5',
    trainerSR: '0'
  },
  todaysJockey: {
    jockeyID: 80669,
    jockeyName: 'robert-dunne',
    jockeyWins: '1',
    jockeyRuns: '9',
    jockeySR: '11'
  },
  horseId: 2630710,
  horseName: 'nightboattoclyro',
  ownerUrl: 'https://www.racingpost.com/profile/owner/283310/glastonburys-on-the-gallops-1',
  breederName: 'Kevin & Anne Glastonbury',
  previousEvents: [
    {
      eventDate: '03Dec20',
      eventName: 'Changed Trainer notification: David Dennis to Samuel Drinkwater'
    },
    { eventDate: '08Nov17', eventName: 'Gelded notification' }
  ],
  stats: {
    runs: 8,
    wins: 3,
    places: 2,
    sr: 38,
    winnings: '13451.00',
    earnings: '14927.00',
    avgWinnings: 1681,
    avgEarnings: 1865,
    bestRpr: NaN,
    bestTs: NaN
  },
  raceRecordTable: [
    {
      lifetimeRecord: 'Hurdle',
      runs: '6',
      wins: '3',
      seconds: '0',
      thirds: '1',
      winnings: '£13,451',
      prize: '14K',
      earnings: '£14,354',
      or: '125',
      bestTs: '105',
      bestRpr: '124',
      bestMr: '—'
    },
    {
      lifetimeRecord: 'NHF',
      runs: '2',
      wins: '0',
      seconds: '0',
      thirds: '1',
      winnings: '—',
      prize: '1K',
      earnings: '£572',
      or: '—',
      bestTs: '75',
      bestRpr: '104',
      bestMr: '—'
    },
    {
      lifetimeRecord: 'Rules Races',
      runs: '8',
      wins: '3',
      seconds: '0',
      thirds: '2',
      winnings: '£13,451',
      prize: '15K',
      earnings: '£14,927',
      or: '—',
      bestTs: '—',
      bestRpr: '—',
      bestMr: '—'
    }
  ],
  formTable: [
    {
      horseId: 2630710,
      lRacecourseId: 12,
      lRaceCourseName: 'chepstow',
      lRaceDate: '2021-01-20',
      lraceId: 774421,
      lJockeyId: 98673,
      lJockeyName: 'jack-tudor',
      lPrizeMoney: 6000,
      lRaceDistance: '2m3½f',
      lRaceDistanceMeters: '2m3½f',
      lGoing: 'Hy',
      lWghtMetric: '65.32',
      lHgr: null,
      lWght: '10-4',
      gearSwitch: false,
      lFinalPos: '1',
      lRan: 6,
      lBeatenBy: undefined,
      lIsNonRunner: false,
      lIsWinner: true,
      lSP: '11/4j',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: 3,
      lOR: 120,
      lTS: 67,
      lRPR: 124,
      lRaceName: 'Thanks To Craig Jones Handicap Hurdle',
      lIsMdn: false,
      lTrackDesc: 'left-handed, galloping, and undulating.',
      lRunComment: 'held up in rear, awkward jump 3rd, headway 3 out, went second before 2 out, switched right after 2 out, shaken up and led approaching last, kept on well (op 9/2)',
      raceDate: '20Jan21',
      raceCourse: 'Chepstow C3HcH 6K',
      raceDistance: '2m3½f',
      going: 'Hy',
      wgt_hgr: '10-4',
      pos_finishPos_winnerRunnerIp_wgt: '1/6 by 2½L First Lord De Cuet 10-9',
      sp: '11/4J',
      jockey: 'J Tudor3',
      or: '120',
      ts: '67',
      rpr: '124',
      mr: '—'
    },
    {
      horseId: 2630710,
      lRacecourseId: 15,
      lRaceCourseName: 'doncaster',
      lRaceDate: '2020-12-11',
      lraceId: 771709,
      lJockeyId: 98673,
      lJockeyName: 'jack-tudor',
      lPrizeMoney: 4000,
      lRaceDistance: '2m½f',
      lRaceDistanceMeters: '2m½f',
      lGoing: 'GS',
      lWghtMetric: '71.67',
      lHgr: null,
      lWght: '11-4',
      gearSwitch: false,
      lFinalPos: '1',
      lRan: 10,
      lBeatenBy: undefined,
      lIsNonRunner: false,
      lIsWinner: true,
      lSP: '9/2',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: 3,
      lOR: 115,
      lTS: 105,
      lRPR: 118,
      lRaceName: 'Sky Sports Racing HD Virgin 535 Handicap Hurdle (Northern Lights Two Mile Hurdle Series Qualifier)',
      lIsMdn: false,
      lTrackDesc: 'left-handed, galloping, flat track',
      lRunComment: 'held up in rear on inner, switched to near side and headway before 3 out, led after 2 out, ridden and kept on well final 110yds (tchd 4/1 and tchd 5/1)',
      raceDate: '11Dec20',
      raceCourse: 'Doncaster C4HcH 4K',
      raceDistance: '2m½f',
      going: 'GS',
      wgt_hgr: '11-4',
      pos_finishPos_winnerRunnerIp_wgt: '1/10 by ¾L Hooper 11-9',
      sp: '9/2',
      jockey: 'J Tudor3',
      or: '115',
      ts: '105',
      rpr: '118',
      mr: '—'
    },
    {
      horseId: 2630710,
      lRacecourseId: 34,
      lRaceCourseName: 'ludlow',
      lRaceDate: '2020-02-19',
      lraceId: 749514,
      lJockeyId: 98673,
      lJockeyName: 'jack-tudor',
      lPrizeMoney: 5000,
      lRaceDistance: '2m5f',
      lRaceDistanceMeters: '2m5f',
      lGoing: 'Sft',
      lWghtMetric: '72.12',
      lHgr: null,
      lWght: '11-5',
      gearSwitch: false,
      lFinalPos: '6',
      lRan: 11,
      lBeatenBy: '9½',
      lIsNonRunner: false,
      lIsWinner: false,
      lSP: '10/1',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: 5,
      lOR: 118,
      lTS: 72,
      lRPR: 110,
      lRaceName: 'Ludlow Racecourse Bookmakers Handicap Hurdle',
      lIsMdn: false,
      lTrackDesc: 'right-handed, sharp track',
      lRunComment: 'held up in rear, ridden and headway before 3 out, no impression from 2 out',
      raceDate: '19Feb20',
      raceCourse: 'Ludlow C4HcH 5K',
      raceDistance: '2m5f',
      going: 'Sft',
      wgt_hgr: '11-5',
      pos_finishPos_winnerRunnerIp_wgt: '6/11 btn 9½L Star Of Rory 11-7',
      sp: '10/1',
      jockey: 'J Tudor5',
      or: '118',
      ts: '72',
      rpr: '110',
      mr: '—'
    },
    {
      horseId: 2630710,
      lRacecourseId: 12,
      lRaceCourseName: 'chepstow',
      lRaceDate: '2020-01-06',
      lraceId: 746618,
      lJockeyId: 98673,
      lJockeyName: 'jack-tudor',
      lPrizeMoney: 4000,
      lRaceDistance: '2m3½f',
      lRaceDistanceMeters: '2m3½f',
      lGoing: 'Hy',
      lWghtMetric: '70.76',
      lHgr: null,
      lWght: '11-2',
      gearSwitch: false,
      lFinalPos: '3',
      lRan: 8,
      lBeatenBy: '26',
      lIsNonRunner: false,
      lIsWinner: false,
      lSP: '13/8',
      lSPDec: '2.6',
      lIsFav: true,
      lJockeyClaim: 7,
      lOR: null,
      lTS: 1,
      lRPR: 112,
      lRaceName: "freebet.com Free Bets Novices' Hurdle",
      lIsMdn: false,
      lTrackDesc: 'left-handed, galloping, and undulating.',
      lRunComment: 'held up in rear, headway before 3 out, 3 lengths third and ridden 2 out, weakened approaching last (op 6/4 tchd 15/8)',
      raceDate: '06Jan20',
      raceCourse: 'Chepstow C4NvH 4K',
      raceDistance: '2m3½f',
      going: 'Hy',
      wgt_hgr: '11-2',
      pos_finishPos_winnerRunnerIp_wgt: '3/8 btn 26L Lieutenant Rocco 11-2',
      sp: '13/8F',
      jockey: 'J Tudor7',
      or: '—',
      ts: '1',
      rpr: '112',
      mr: '—'
    },
    {
      horseId: 2630710,
      lRacecourseId: 12,
      lRaceCourseName: 'chepstow',
      lRaceDate: '2019-12-07',
      lraceId: 744506,
      lJockeyId: 98673,
      lJockeyName: 'jack-tudor',
      lPrizeMoney: 4000,
      lRaceDistance: '2m3½f',
      lRaceDistanceMeters: '2m3½f',
      lGoing: 'Sft',
      lWghtMetric: '65.77',
      lHgr: null,
      lWght: '10-5',
      gearSwitch: false,
      lFinalPos: '1',
      lRan: 15,
      lBeatenBy: undefined,
      lIsNonRunner: false,
      lIsWinner: true,
      lSP: '50/1',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: 7,
      lOR: null,
      lTS: 75,
      lRPR: 118,
      lRaceName: "UHY Hacker Young Novices' Hurdle",
      lIsMdn: false,
      lTrackDesc: 'left-handed, galloping, and undulating.',
      lRunComment: 'held up behind, good headway after 7th, led after 2 out, strongly challenged after last, held on, all out (op 40/1 tchd 33/1)',
      raceDate: '07Dec19',
      raceCourse: 'Chepstow C4NvH 4K',
      raceDistance: '2m3½f',
      going: 'Sft',
      wgt_hgr: '10-5',
      pos_finishPos_winnerRunnerIp_wgt: '1/15 by ½L Meyer Lansky 10-12',
      sp: '50/1',
      jockey: 'J Tudor7',
      or: '—',
      ts: '75',
      rpr: '118',
      mr: '—'
    },
    {
      horseId: 2630710,
      lRacecourseId: 73,
      lRaceCourseName: 'taunton',
      lRaceDate: '2019-11-14',
      lraceId: 742258,
      lJockeyId: 91162,
      lJockeyName: 'jamie-bargary',
      lPrizeMoney: 4000,
      lRaceDistance: '2m½f',
      lRaceDistanceMeters: '2m½f',
      lGoing: 'Gd',
      lWghtMetric: '69.85',
      lHgr: null,
      lWght: '11-0',
      gearSwitch: false,
      lFinalPos: 'BD',
      lRan: 14,
      lBeatenBy: undefined,
      lIsNonRunner: false,
      lIsWinner: false,
      lSP: '50/1',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: null,
      lOR: null,
      lTS: null,
      lRPR: 101,
      lRaceName: 'Fuelled By Verm-X Maiden Hurdle (Div I)',
      lIsMdn: true,
      lTrackDesc: 'right-handed, sharp track',
      lRunComment: 'held up in rear, nudged along and some headway after 3 out, keeping on when brought down 2 out (op 33/1)',
      raceDate: '14Nov19',
      raceCourse: 'Taunton C5MdH 4K',
      raceDistance: '2m½f',
      going: 'Gd',
      wgt_hgr: '11-0',
      pos_finishPos_winnerRunnerIp_wgt: 'BD/14 Bathsheba Bay 11-0',
      sp: '50/1',
      jockey: 'J Bargary',
      or: '—',
      ts: '—',
      rpr: '101',
      mr: '—'
    },
    {
      horseId: 2630710,
      lRacecourseId: 1212,
      lRaceCourseName: 'ffos-las',
      lRaceDate: '2019-05-25',
      lraceId: 728768,
      lJockeyId: 88023,
      lJockeyName: 'sam-twiston-davies',
      lPrizeMoney: 2000,
      lRaceDistance: '2m',
      lRaceDistanceMeters: '2m',
      lGoing: 'Gd',
      lWghtMetric: '70.76',
      lHgr: null,
      lWght: '11-2',
      gearSwitch: false,
      lFinalPos: '6',
      lRan: 6,
      lBeatenBy: '9¾',
      lIsNonRunner: false,
      lIsWinner: false,
      lSP: '8/1',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: null,
      lOR: null,
      lTS: 22,
      lRPR: 101,
      lRaceName: 'Pendine Sands Holiday Park Intermediate Open National Hunt Flat Race',
      lIsMdn: false,
      lTrackDesc: 'left-handed, flat, galloping',
      lRunComment: 'took keen hold, tracked leaders, ridden over 3f out, weakened approaching final furlong (tchd 7/1)',
      raceDate: '25May19',
      raceCourse: 'Ffos Las C5NHF 2K',
      raceDistance: '2m',
      going: 'Gd',
      wgt_hgr: '11-2',
      pos_finishPos_winnerRunnerIp_wgt: '6/6 btn 9¾L Jac Brown 10-9',
      sp: '8/1',
      jockey: 'S Twiston-Davies',
      or: '—',
      ts: '22',
      rpr: '101',
      mr: '—'
    },
    {
      horseId: 2630710,
      lRacecourseId: 34,
      lRaceCourseName: 'ludlow',
      lRaceDate: '2019-04-23',
      lraceId: 726112,
      lJockeyId: 88023,
      lJockeyName: 'sam-twiston-davies',
      lPrizeMoney: 4000,
      lRaceDistance: '2m',
      lRaceDistanceMeters: '2m',
      lGoing: 'Gd',
      lWghtMetric: '70.76',
      lHgr: null,
      lWght: '11-2',
      gearSwitch: false,
      lFinalPos: '3',
      lRan: 4,
      lBeatenBy: '10',
      lIsNonRunner: false,
      lIsWinner: false,
      lSP: '5/2',
      lSPDec: null,
      lIsFav: false,
      lJockeyClaim: null,
      lOR: null,
      lTS: 75,
      lRPR: 104,
      lRaceName: 'Perrott Properties Ltd Intermediate Open National Hunt Flat Race',
      lIsMdn: false,
      lTrackDesc: 'right-handed, sharp track',
      lRunComment: 'raced keenly in last, went 3rd under pressure 3f out, soon driven and outpaced by leading pair, kept on',
      raceDate: '23Apr19',
      raceCourse: 'Ludlow C4NHF 4K',
      raceDistance: '2m',
      going: 'Gd',
      wgt_hgr: '11-2',
      pos_finishPos_winnerRunnerIp_wgt: '3/4 btn 10L Bergamot 10-4',
      sp: '5/2',
      jockey: 'S Twiston-Davies',
      or: '—',
      ts: '75',
      rpr: '104',
      mr: '—'
    }
  ],
  declaredComment: 'Comment:Improving 7yo and with barely any weight he could easily make presence felt.'
}
]